# Generated by Django 6.0.6 on 2026-07-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_skills_vacancy_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Baкансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
